### ISSUE TITLE
Modernize dependency management from dep to vgo

### ISSUE THREAD

**Issue by bruceadowns** [lightstep/lightstep-tracer-common#37]
This issue will cover work related to converting from dep to go modules.

Background on go modules can be found at https://github.com/golang/go/wiki/Modules.

**Comment by bruceadowns** [comment]
Conversation will cover converting both lightstep-tracer-common and lightlightstep-tracer-go.

**Comment by bruceadowns** [comment]
Updating the build process from dep to vgo should also include updating these containers:

https://hub.docker.com/r/lightstep/gogoprotoc
https://hub.docker.com/r/lightstep/gobuild

@austinlparker, is the source for these publicly available?

Note, updating these containers is not strictly necessary, but would be a good idea since we're in here already.

**Comment by bruceadowns** [comment]
Work thus far has included:
* generating go.mod and go.sum based on Gopkg.lock and Gopkg.toml
* deleting Gopkg.lock and Gopkg.toml
* updating circleci to golang:1.12
* updating genproto.mk to align with GO111MODULE behavior
* updating the make files to reflect GO111MODULE behavior
* refining gitignore

**Comment by austinlparker** [comment]
Let me check on those containers and get back to you — I don’t think there’s a reason they should be private, but they may have refs to our monorepo. Thanks for taking a crack at this!

**Comment by austinlparker** [comment]
Looks like gogoprotoc can get made public, and we can refactor to remove the dependency on gobuild (see https://github.com/lightstep/lightstep-tracer-go/commit/5555a6b85a341d7b1a0b9f6412bd82a0c387f9c9 for the relevant commit)

**Comment by bruceadowns** [comment]
> we can refactor to remove the dependency on gobuild

Cool. I'll digest that commit and reconcile how to apply it here.

**Comment by bruceadowns** [comment]
Thanks for the info @austinlparker!

I've reviewed the noted commit and code, but all moving parts are not immediately clear. My first step is to further understand your usage of protobuf and gogo. That way I can coalesce how they relate to the build process.

**Comment by bruceadowns** [comment]
I've been traveling and this issue stalled around the somewhat related gogoprotoc and gobuild containers. I will create 2 PRs to restart the conversation in order to update to `go modules`.
