### ISSUE TITLE
License confirmation

### ISSUE THREAD

**Issue by pfmackin** [lightstep/lightstep-tracer-common#41]
Hi, could you please confirm that the MIT license or some other license applies to the code in this repo?  Thanks for your help.

**Comment by pfmackin** [comment]
@iredelmeier Hi, I noticed you just updated the CONTRIBUTING.md file.  I was wondering if you could either put a license in the repo or confirm what license is used.  Thanks in advance for your help.

**Comment by carlosalberto** [comment]
hey @pfmackin 

We should be doing today/tomorrow a pass to add LICENSE info where it's missing - and for the record, we will be using MIT license ;)

**Comment by pfmackin** [comment]
Excellent, thanks for your quick response.

Paul

**Comment by pfmackin** [comment]
Thank you for adding the license.
